### ISSUE TITLE
Error importing minisam module in Python

### ISSUE THREAD

**Issue by wugeshenhuaking** [dongjing3309/minisam#29]
When I execute the following command
`from minisam import *`
I got an error report
`Traceback (most recent call last):
  File "/home/wyw/codeProjects/pyProj/PyICP-SLAM/main_icp_slam.py", line 15, in <module>
    from minisam import *
  File "/home/wyw/anaconda3/envs/python_robotics/lib/python3.10/site-packages/minisam-0.0.0-py3.10.egg/minisam/__init__.py", line 3, in <module>
ModuleNotFoundError: No module named 'minisam._minisam_py_wrapper'`

**Comment by wugeshenhuaking** [comment]
This is the output of my Python package installation according to the document
`wyw@wyw-ros:~/GitRepository/minisam/build$ sudo make install
[ 68%] Built target minisam
[ 73%] Built target robust_curve_fitting
[ 78%] Built target optimize_custom_type
[100%] Built target _minisam_py_wrapper
[100%] Built target python_package
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/include/minisam/config.h
-- Up-to-date: /usr/local/include/minisam/core/Eigen.h
-- Up-to-date: /usr/local/include/minisam/core/Factor.h
-- Up-to-date: /usr/local/include/minisam/core/FactorGraph.h
-- Up-to-date: /usr/local/include/minisam/core/Key.h
-- Up-to-date: /usr/local/include/minisam/core/LossFunction.h
-- Up-to-date: /usr/local/include/minisam/core/Scalar.h
-- Up-to-date: /usr/local/include/minisam/core/SchurComplement.h
-- Up-to-date: /usr/local/include/minisam/core/Traits.h
-- Up-to-date: /usr/local/include/minisam/core/Variable.h
-- Up-to-date: /usr/local/include/minisam/core/VariableOrdering.h
-- Up-to-date: /usr/local/include/minisam/core/Variables.h
-- Up-to-date: /usr/local/include/minisam/linear/AMDOrdering.h
-- Up-to-date: /usr/local/include/minisam/linear/ConjugateGradient.h
-- Up-to-date: /usr/local/include/minisam/linear/Covariance.h
-- Up-to-date: /usr/local/include/minisam/linear/DenseCholesky.h
-- Up-to-date: /usr/local/include/minisam/linear/LinearSolver.h
-- Up-to-date: /usr/local/include/minisam/linear/Ordering.h
-- Up-to-date: /usr/local/include/minisam/linear/SchurComplementDenseSolver.h
-- Up-to-date: /usr/local/include/minisam/linear/SparseCholesky.h
-- Up-to-date: /usr/local/include/minisam/linear/SquareRoot.h
-- Up-to-date: /usr/local/include/minisam/linear/SquareRootCholesky.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/DoglegOptimizer.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/GaussNewtonOptimizer.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/LevenbergMarquardtOptimizer.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/MarginalCovariance.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/NonlinearOptimizer.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/NumericalFactor.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/SparsityPattern.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/linearization.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/numericalJacobian.h
-- Up-to-date: /usr/local/include/minisam/nonlinear/numericalJacobianImpl.h
-- Up-to-date: /usr/local/include/minisam/utils/Timer.h
-- Up-to-date: /usr/local/include/minisam/utils/testAssertions.h
-- Up-to-date: /usr/local/include/minisam/linear/cholmod/Cholmod.h
-- Up-to-date: /usr/local/include/minisam/linear/spqr/SPQR.h
-- Up-to-date: /usr/local/lib/libminisam.so
-- Up-to-date: /usr/local/include/minisam/3rdparty/eigen3
-- Up-to-date: /usr/local/include/minisam/3rdparty/eigen3/COPYING.LGPL
-- Up-to-date: /usr/local/include/minisam/3rdparty/eigen3/src
-- Up-to-date: /usr/local/include/minisam/3rdparty/eigen3/src/OrderingMethods
-- Up-to-date: /usr/local/include/minisam/3rdparty/eigen3/src/OrderingMethods/Ordering.h
-- Up-to-date: /usr/local/include/minisam/3rdparty/eigen3/src/OrderingMethods/Amd.h
-- Up-to-date: /usr/local/include/minisam/3rdparty/eigen3/OrderingMethods
-- Up-to-date: /usr/local/include/minisam/3rdparty/eigen3/README.txt
-- Up-to-date: /usr/local/lib/cmake/minisam/minisam-export.cmake
-- Up-to-date: /usr/local/lib/cmake/minisam/minisam-export-release.cmake
-- Up-to-date: /usr/local/lib/cmake/minisam/minisam-config.cmake
running install
/home/wyw/anaconda3/envs/python_robotics/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/wyw/anaconda3/envs/python_robotics/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating minisam.egg-info
writing minisam.egg-info/PKG-INFO
writing dependency_links to minisam.egg-info/dependency_links.txt
writing top-level names to minisam.egg-info/top_level.txt
writing manifest file 'minisam.egg-info/SOURCES.txt'
reading manifest file 'minisam.egg-info/SOURCES.txt'
writing manifest file 'minisam.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/minisam
copying /home/wyw/GitRepository/minisam/python/minisam/__init__.py -> build/lib/minisam
copying /home/wyw/GitRepository/minisam/python/minisam/_minisam_py_wrapper.cpython-310-x86_64-linux-gnu.so -> build/lib/minisam
copying /home/wyw/GitRepository/minisam/python/minisam/libminisam.so -> build/lib/minisam
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/minisam
copying build/lib/minisam/__init__.py -> build/bdist.linux-x86_64/egg/minisam
copying build/lib/minisam/_minisam_py_wrapper.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/minisam
copying build/lib/minisam/libminisam.so -> build/bdist.linux-x86_64/egg/minisam
byte-compiling build/bdist.linux-x86_64/egg/minisam/__init__.py to __init__.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying minisam.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying minisam.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying minisam.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying minisam.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/minisam-0.0.0-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing minisam-0.0.0-py3.10.egg
Removing /home/wyw/anaconda3/envs/python_robotics/lib/python3.10/site-packages/minisam-0.0.0-py3.10.egg
Copying minisam-0.0.0-py3.10.egg to /home/wyw/anaconda3/envs/python_robotics/lib/python3.10/site-packages
minisam 0.0.0 is already the active version in easy-install.pth

Installed /home/wyw/anaconda3/envs/python_robotics/lib/python3.10/site-packages/minisam-0.0.0-py3.10.egg
Processing dependencies for minisam==0.0.0
Finished processing dependencies for minisam==0.0.0`

**Comment by Shubham-2302** [comment]
Did you solve the error?
